### ISSUE TITLE
Project Review: Summary

### ISSUE THREAD

**Issue by SidTheEngineer** [tina-pina/expresso#1]
### Criteria 1: Table Creation (Migration File)
* _Score Level:_ 4/4
* _Comment(s):_ Nice work with your `migration.js` file. All of the correct data types are used and relationships between the tables look correct 👍 
 
### Criteria 2: Implementation of API Specification and Functionality
* _Score Level:_ 4/4
* _Comment(s):_ Overall nice work with the API implementation. All of the routes work appropriately, errors are handled, and functionality works as it should throughout the app 💯.
 
### Criteria 3: Test Case Results (Are all Test Cases Passing?)
* _Score Level:_ 4/4
* _Comment(s):_ All test cases are passing ✅ 
 
### Criteria 4: JavaScript and Express.js Fundamentals and Formatting
* _Score Level:_ 4/4
* _Comment(s):_ Your code looks solid throughout the project. I don't see any glaring issues with syntax/formatting that need to be fixed. Express tools such as middleware, route parameters, etc are all used appropriately as well. Nice work here!

**Comment by tina-pina** [comment]
Thank you very much for the review! :)
